# Generated by Django 2.2.5 on 2019-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='variable_default_values',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='variable_names',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
