# Generated by Django 2.2.5 on 2019-09-10 23:30

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_resources_20190911_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IC', 'In Class'), ('LL', 'Language Learning'), ('FS', 'Further Study')], default=('IC', 'In Class'), max_length=2)),
                ('link_URL', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='solution_release_datetime',
            field=models.DateTimeField(default=courses.models.Worksheet.default_release_date),
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IC', 'In Class'), ('LL', 'Language Learning'), ('FS', 'Further Study')], default=('IC', 'In Class'), max_length=2)),
                ('link_URL', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
