# Generated by Django 2.2.5 on 2019-09-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_recreate_resources_20190911_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='SharedResource',
        ),
    ]
