# Generated by Django 2.2.5 on 2019-09-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_sharedresource_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='calculated_answer',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
