# Generated by Django 2.2.6 on 2019-11-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_problem_answer_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResource',
        ),
    ]
