# Generated by Django 2.2.6 on 2019-11-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_delete_courseresource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedResource',
            new_name='CourseResource',
        ),
    ]
