# Generated by Django 3.0.2 on 2020-01-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('courses', '0013_auto_20191102_1219'), ('courses', '0014_auto_20191102_1236')]

    dependencies = [
        ('courses', '0012_delete_courseresource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedResource',
            new_name='Resource',
        ),
    ]
