# Generated by Django 2.2.6 on 2019-11-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20191102_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResource',
            new_name='Resource',
        ),
    ]
