# Generated by Django 2.2.6 on 2019-11-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20191102_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link0_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link1_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link2_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link3_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
