# Generated by Django 3.0.2 on 2020-01-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20191102_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
