# Generated by Django 3.0.2 on 2020-02-01 04:21

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200123_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=martor.models.MartorField(default='Your question here.', max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=martor.models.MartorField(default='The solution to this problem is not available yet.', max_length=1000),
        ),
    ]
