# Generated by Django 3.0.2 on 2020-02-01 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200201_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nen_kumi',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Middle School classes: A-E or High School classes: 1-8', regex='[1-3]-([A-E]|[1-8])')]),
        ),
    ]
