# Generated by Django 3.0.2 on 2020-02-01 18:21
# https://docs.djangoproject.com/en/2.2/topics/migrations/#data-migrations

from django.db import migrations
from django.db.utils import OperationalError

from courses.models import Course


def populate_nen_kumi(apps, schema_editor):
    """Data migration."""
    try:
        for course in Course.objects.all():
            course.nen_kumi = '{}-{}'.format(course.nen, course.kumi)
            course.save()
    except OperationalError:
        """Suppress this error when the data migration is reapplied."""
        pass
    
def unpopulate_nen_kumi(apps, schema_editor):
    """Data migration."""
    try:
        for course in Course.objects.all():
            course.nen_kumi = ''
            course.save()
    except OperationalError:
        """Suppress this error when the data migration is reapplied."""
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_nen_kumi'),
    ]

    operations = [
        migrations.RunPython(populate_nen_kumi, unpopulate_nen_kumi),
    ]
