# Generated by Django 3.0.2 on 2020-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_populate_nen_kumi'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='variables_with_values',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
