# Generated by Django 3.0.2 on 2020-02-02 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_populate_variables_with_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='variable_default_values',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='variable_names',
        ),
    ]
