# Generated by Django 3.0.2 on 2020-02-02 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_populate_variables_with_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='variable_default_values',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='variable_names',
        ),
        migrations.AlterField(
            model_name='problem',
            name='variables_with_values',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Variables format is variable_name[default_value, min, max, step].', regex='(([a-z|A-Z]\\w*)\\[(([0-9]+\\.?[0-9]*)(,\\s)?){0,3}([0-9]+\\.?[0-9]*)\\](,\\s)?)*')]),
        ),
    ]
