# Generated by Django 3.0.2 on 2020-02-02 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_old_variable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='variables_with_values',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Variables format is variable_name[default_value, min, max, step].', regex='([a-z|A-Z]\\w*\\[([0-9]+(\\.?[0-9]*e?[0-9]{0,3})(,\\s)?){0,3}([0-9]+\\.?[0-9]*e?[0-9]{0,3}\\])(,\\s)?)*')]),
        ),
    ]
