# Generated by Django 3.0.2 on 2020-02-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_update_variables_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='nen_kumi',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
