# Generated by Django 3.0.2 on 2020-02-07 02:42

import courses.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_cleaning_up_course_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=courses.models.Lesson.default_lesson_date),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
        ),
    ]
