# Generated by Django 3.0.2 on 2020-02-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_cleaning_up_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='course',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
