# Generated by Django 3.0.2 on 2020-02-11 00:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_allow_worksheet_without_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term1_start',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 1, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='term2_start',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 1, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='term3_start',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 1, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='term4_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2019, message='No courses before 2019.')]),
        ),
    ]
